const CustomerReviews = [
  {
    id: 0,
    rating: 5,
    title: "Exceptional Service!",
    text: "Our experience with Estatein was outstanding. Their team's dedication and professionalism made finding our dream home a breeze. Highly recommended!",
    userImg: "/esta/assets/home/user-img.png",
    userName: "Wade Warren",
    userCountry: "USA, California",
  },
  {
    id: 1,
    rating: 5,
    title: "Efficient and Reliable",
    text: "Estatein provided us with top-notch service. They helped us sell our property quickly and at a great price. We couldn't be happier with the results.",
    userImg: "/esta/assets/home/user-img1.png",
    userName: "Emelie Thomson",
    userCountry: "USA, Florida",
  },
  {
    id: 2,
    rating: 5,
    title: "Trusted Advisors",
    text: "The Estatein team guided us through the entire buying process. Their knowledge and commitment to our needs were impressive. Thank you for your support!",
    userImg: "/esta/assets/home/user-img2.png",
    userName: "John Mans",
    userCountry: "USA, Nevada",
  },
  {
    id: 3,
    rating: 5,
    title: "Exceptional Service!",
    text: "Our experience with Estatein was outstanding. Their team's dedication and professionalism made finding our dream home a breeze. Highly recommended!",
    userImg: "/esta/assets/home/user-img.png",
    userName: "Wade Warren",
    userCountry: "USA, California",
  },
  {
    id: 4,
    rating: 5,
    title: "Efficient and Reliable",
    text: "Estatein provided us with top-notch service. They helped us sell our property quickly and at a great price. We couldn't be happier with the results.",
    userImg: "/esta/assets/home/user-img1.png",
    userName: "Emelie Thomson",
    userCountry: "USA, Florida",
  },
  {
    id: 5,
    rating: 5,
    title: "Trusted Advisors",
    text: "The Estatein team guided us through the entire buying process. Their knowledge and commitment to our needs were impressive. Thank you for your support!",
    userImg: "/esta/assets/home/user-img2.png",
    userName: "John Mans",
    userCountry: "USA, Nevada",
  },
  {
    id: 6,
    rating: 5,
    title: "Exceptional Service!",
    text: "Our experience with Estatein was outstanding. Their team's dedication and professionalism made finding our dream home a breeze. Highly recommended!",
    userImg: "/esta/assets/home/user-img.png",
    userName: "Wade Warren",
    userCountry: "USA, California",
  },
  {
    id: 7,
    rating: 5,
    title: "Efficient and Reliable",
    text: "Estatein provided us with top-notch service. They helped us sell our property quickly and at a great price. We couldn't be happier with the results.",
    userImg: "/esta/assets/home/user-img1.png",
    userName: "Emelie Thomson",
    userCountry: "USA, Florida",
  },
  {
    id: 8,
    rating: 5,
    title: "Trusted Advisors",
    text: "The Estatein team guided us through the entire buying process. Their knowledge and commitment to our needs were impressive. Thank you for your support!",
    userImg: "/esta/assets/home/user-img2.png",
    userName: "John Mans",
    userCountry: "USA, Nevada",
  },
  {
    id: 10,
    rating: 5,
    title: "Exceptional Service!",
    text: "Our experience with Estatein was outstanding. Their team's dedication and professionalism made finding our dream home a breeze. Highly recommended!",
    userImg: "/esta/assets/home/user-img.png",
    userName: "Wade Warren",
    userCountry: "USA, California",
  },
  {
    id: 11,
    rating: 5,
    title: "Efficient and Reliable",
    text: "Estatein provided us with top-notch service. They helped us sell our property quickly and at a great price. We couldn't be happier with the results.",
    userImg: "/esta/assets/home/user-img1.png",
    userName: "Emelie Thomson",
    userCountry: "USA, Florida",
  },
  {
    id: 12,
    rating: 5,
    title: "Trusted Advisors",
    text: "The Estatein team guided us through the entire buying process. Their knowledge and commitment to our needs were impressive. Thank you for your support!",
    userImg: "/esta/assets/home/user-img2.png",
    userName: "John Mans",
    userCountry: "USA, Nevada",
  },
];

export default CustomerReviews;
